### ISSUE TITLE
Where is Chat, register_call functions?

### ISSUE THREAD

**Issue by dsbyprateekg** [ahmadfaizalbh/Chatbot#21]
**Describe the bug**
After cloning the code, installing the setup file when I run the demo code for wiki search, I am getting `ImportError: cannot import name 'register_call' from 'chatbot'` error

**To Reproduce**
1. run Example.py

**Expected behavior**
code should run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Python 3.7
 - Browser Chrome

**Additional context**
`from chatbot import Chat, register_call
ImportError: cannot import name 'register_call' from 'chatbot'`

**Comment by ahmadfaizalbh** [comment]
Looks like you have installed older version of library 

Please run below script to upgrade your library version
```bash
pip3 install --upgrade chatbotai
```

**Comment by dsbyprateekg** [comment]
Thanks.
After updating the library to 0.2.1.1, I am able to run the code successfully.
Please close the ticket.
